export const iconListComponents = {
  dashboard: "dashboard",
  users: "users",
  map: "map",
  file: "file",
  briefcase: "briefcase",
  calendar: "calendar",
  report: "report",
  wallet: "wallet",
  settings: "settings",
  help: "help",
  chevronsLeft: "chevronsLeft",
  chevronsRight: "chevronsRight",
  search: "search",
  logout: "logout",
  back: "back",
  check: "check",
  download: "download",
} as const;
